{% set name = "zntrack" %}
{% set version = "0.8.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zntrack-{{ version }}.tar.gz
  sha256: d03785dc675db0941e7401c4c3e7ed29d3f1e6af70905e6e5c6817f2a759e2f1

build:
  entry_points:
    - zntrack = zntrack.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - dvc >=3.50.0,<4.0.0
    - pyyaml >=6.0.0,<7.0.0
    - tqdm >=4.0.0,<5.0.0
    - znjson >=0.2.0,<0.3.0
    - znflow >=0.2.2,<0.3.0
    - typer >=0.13.0,<0.14.0
    - znfields >=0.1.2,<0.2.0
    - pandas >=2.0.0,<3.0.0

test:
  imports:
    - zntrack
  commands:
    - pip check
    - zntrack --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/zincware/ZnTrack
  summary: Create, Run and Benchmark DVC Pipelines in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
