{% set name = "zntrack" %}
{% set version = "0.8.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zntrack-{{ version }}.tar.gz
  sha256: 681dbc9310654dafb0178db17fb2c18ec7c2b3accf32a24ac00a61849c930046

build:
  entry_points:
    - zntrack = zntrack.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - dvc >=3.59.0
    - pyyaml >=6.0.2
    - tqdm >=4.67.1
    - znjson >=0.2.6
    - znflow >=0.2.5
    - typer >=0.15.1
    - znfields >=0.1.2
    - pandas >=2.2.3

test:
  imports:
    - zntrack
  commands:
    - pip check
    - zntrack --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/zincware/ZnTrack
  summary: Create, Run and Benchmark DVC Pipelines in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
